export default [
  {
    title:'首页',
    key:'/admin/home'
  },
  {
    title:'UI',
    key:'/admin/ui',
    children:[
      {
        title:'按钮',
        key:'/admin/ui/button'
      },
      {
        title:'弹框',
        key:'/admin/ui/alert'
      },
      {
        title:'加载',
        key:'/admin/ui/loading'
      }
    ]
  },
  {
    title:'用户管理',
    key:'/admin/user',
    children:[
      {
        title:'添加用户',
        key:'/admin/user/add'
      },
      {
        title:'用户列表',
        key:'/admin/user/list'
      },
    ]
  },
  {
    title:'权限管理',
    key:'/admin/level',
    children:[
      {
        title:'页面权限',
        key:'/admin/level/page'
      },
    ]
  }
]